### PR TITLE
Update get-to-know-hatch.md for consistent style of "Hatch" etc.

### PR DESCRIPTION
**Pull request by ptressel**
Use "Hatch" to refer to the tool, "hatch" to the command.  Use fixed-pitch text for commands and file names.  Add missing periods.  Note there is one sentence re. comparing Hatch to other tools, where their names are all lowercase, but I don't know if the other tools are commonly referred to that way.

### CODE REVIEW

**Review by ucodery — APPROVED** [review]

**Review by lwasser — APPROVED** [review]
This looks good to me as well!! thanks @ptressel there was a merge conflict and i *thijnk* i resolved it in a way that aligned with your intent. but feel free to have a look in case i didn't. i'm approving this for merge however as well! i think it's ready to go!

**Comment by lwasser** [comment]
hello there @ptressel - it also looks like we have a bad link in ci - if you see here - https://github.com/pyOpenSci/python-package-guide/actions/runs/8694415211/job/23843264627?pr=227#step:12:26

**Comment by ptressel** [comment]
Ok, thanks for catching those @lwasser !  I'll come back after the end of Tax Day to have a look.  :D

**Comment by lwasser** [comment]
@ptressel ahhh tax day 😆 i know that feeling!! no rush on this at all!! ✨

**Comment by lwasser** [comment]
ok! this is looking good. I am going to merge it and we can alway fix more things if we need to in the future! thank you again @ptressel !!

**Review by lwasser — APPROVED** [review]
approved!

**Pull request merged**
