### PR TITLE
update version from 0.1.0 to 0.1

### PR DESCRIPTION
**Pull request by pb-413**
Represent version in a consistent way for issue #257

### CODE REVIEW

**Comment by ucodery** [comment]
Could you please fix the other two versions in this file? lines 452 and 580 currently.

**Comment by pb-413** [comment]
> Could you please fix the other two versions in this file? lines 452 and 580 currently.

Got it!

**Review by ucodery — APPROVED** [review]

**Comment by ucodery** [comment]
Thanks for this!

**Comment by lwasser** [comment]
@all-contributors  please add @pb-413 for code, review 

thank you both!! @ucodery i wonder if you are able to call the contributor bot. we can always go back and do it but you are welcome to add contribs too if that feels comfortable to you!

**Pull request merged**
