### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by dpprdan**
This fixes (what I believe to be) two typos.

### CODE REVIEW

**Review by lwasser — APPROVED** [review]
Thank you for these edits! i'm going to let ci run and then will merge this!!

**Comment by lwasser** [comment]
@all-contributors please add @dpprdan for code, review

**Comment by lwasser** [comment]
wonderful - all checks passed! merging this now. @dpprdan may i ask - how did you find us here??

**Comment by dpprdan** [comment]
@lwasser I think it was something like (ropensci?!) -> your [mastodon](https://fosstodon.org/@leahawasser/110101561641074327) account -> the [demystifying python packaging](https://www.pyopensci.org/blog/demystifying-python-packaging.html) blog post -> [Python Package Guide](https://www.pyopensci.org/python-package-guide/package-structure-code/intro.html).

I am dabbling with python packaging ATM and took the Poetry (also via https://py-pkgs.org/) route for now. Looking forward to more content in the Python Package Guide 😄

**Pull request merged**
