### PR TITLE
chore: add prettier to pre-commit hook configuration

### PR DESCRIPTION
**Pull request by tkoyama010**
Add prettier to pre-commit hook configuration.
ref [PC180 in Scientific Python Library Development Guide](https://learn.scientific-python.org/development/guides/style/#prettier).

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
apre-commit.ci autofix

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by lwasser — APPROVED** [review]
Neat! i haven't used prettier before but have wanted to check it out. thank you. this also can be merged once Ci is happy.

**Pull request merged**
