### PR TITLE
docs: preparing the Translation Files for Japanese

### LINKED ISSUE #352: I would like to start the translation of the guide into Japanese
I would like to start the translation of the guide into Japanese  based on [Starting a New Language Translation](https://github.com/pyOpenSci/python-package-guide/blob/main/TRANSLATING.md#starting-a-new-language-translation) :rocket:

### PR DESCRIPTION
**Pull request by tkoyama010**
resolve #352
ref [Preparing the Translation Files](https://github.com/pyOpenSci/python-package-guide/blob/main/TRANSLATING.md#preparing-the-translation-files)

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
Once this PR is merged, proceed to the next step of [Translation Guide for the Python Packaging Guide](https://github.com/pyOpenSci/python-package-guide/blob/main/TRANSLATING.md#translation-guide-for-the-python-packaging-guide).

**Review by flpm — COMMENTED** [review]
Thanks for excluding the changes on the "es" files! The only comment is that we should use the [iso code](https://en.m.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) for Japanese (jp) instead of ja for the folder.

**Comment by tkoyama010** [comment]
> Thanks for excluding the changes on the "es" files! The only comment is that we should use the [iso code](https://en.m.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) for Japanese (jp) instead of ja for the folder.

Good catch. Thanks!

**Comment by tkoyama010** [comment]
> Thanks for excluding the changes on the "es" files! The only comment is that we should use the [iso code](https://en.m.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) for Japanese (jp) instead of ja for the folder.

The code language option for Japanese is ja in [Sphinx Options for internationalization](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language). Could you explain the reason we use iso code?

**Comment by tkoyama010** [comment]
The Wikipedia description is most likely incorrect :cry: : `jp` is the **Japan** code and `ja` is the **Japanese** code.

**Comment by flpm** [comment]
Interesting, good catch! I wonder why they deviated from the standard. Keeping to the standard helps with language detection, so tools can recognize that a locale exists for a certain language automatically.

In our case, the important part is matching the theme locale code, because part of the text that appears comes from the Sphinx theme (pydata) and for it to work well they have to match.

I just checked and the [theme does not have a Japanese locale yet](https://github.com/pydata/pydata-sphinx-theme/tree/main/src/pydata_sphinx_theme/locale), so no answer there.

I think it's probably better then to stick to the Sphinx code (ja), assuming that is what themes would also choose for their locales.

**Comment by tkoyama010** [comment]
Thanks, it seems that Wikipedia was not wrong but the part I was referring to. The codes are different for country codes and language codes, and for language codes it is correct to look at [IETF language tag](https://en.m.wikipedia.org/wiki/IETF_language_tag). I will send a separate Pull Request for this!

**Comment by flpm** [comment]
> The Wikipedia description is most likely incorrect :cry: : `jp` is the **Japan** code and `ja` is the **Japanese** code.

Ah, I guess it makes more sense then. We should then refer to the language, ja would be the correct code to use.

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
I have no idea about CI error🙇

**Comment by willingc** [comment]
Hi @tkoyama010. #356 should fix the htmlproofer error. Thanks for this PR :tada:

**Comment by lwasser** [comment]
@all-contributors please add @tkoyama010 for code, review

**Comment by lwasser** [comment]
hey @flpm i'm happy for you to merge these translation related pr's as you see fit if you are ok with doing so!

**Review by flpm — APPROVED** [review]
Looks good to me. It's exciting to start a new language translation!

**Pull request merged**
