### PR TITLE
docs: change update translation sessions in nox

### PR DESCRIPTION
**Pull request by flpm**
## What was done

Following the discussion in PR #397, this PR makes the following changes:
- Modify the `update-translations` session to only update translation files for languages in `RELEASE_LANGUAGES`.
- Added a new nox session `update-langugage` that can be used to update the translation files for a specific language.

This PR also fixes a small syntax issue in the `documentation.po` file for the Spanish translation (missing quote).

## How to test

Run `nox -s update-translations` and confirm in the output that no languages are updated
```
❯ nox -s update-translations
nox > Running session update-translations
nox > Re-using existing virtual environment at .nox/update-translations.
nox > No release languages defined in RELEASE_LANGUAGES
nox > Session update-translations was successful.
```

Run `nox -s update-language -- es` and verify that the .po files for the Spanish translation are updated
```
❯ nox -s update-language -- es
(... some lines removed ...)
The message catalogs are in _build/gettext.
nox > Updating .po files for [es] translation
nox > sphinx-intl update -p _build/gettext -l es
Update: locales/es/LC_MESSAGES/tests.po +1, -1
Update: locales/es/LC_MESSAGES/documentation.po +1, -1
Update: locales/es/LC_MESSAGES/index.po +2, -2
Update: locales/es/LC_MESSAGES/tutorials.po +41, -19
Update: locales/es/LC_MESSAGES/TRANSLATING.po +2, -2
Update: locales/es/LC_MESSAGES/CONTRIBUTING.po +68, -15
Update: locales/es/LC_MESSAGES/package-structure-code.po +18, -18
nox > Session update-language was successful.
```

### CODE REVIEW

**Comment by sneakers-the-rat** [comment]
minor thing: i wonder if we can pick one term to refer to a translation or language? currently we have something like this

<table><thead><tr><th></th><th>update<br></th><th>build<br></th></tr></thead><tbody><tr><td>single<br></td><td>`update_language`<br></td><td>`build_languages`<br></td></tr><tr><td>multi<br></td><td>`update_translations`<br></td><td>`build_translations`</td></tr></tbody></table>

i don't have a strong preference between four sessions vs two sessions s.t. with no arguments they build/update all languages but with an argument only update a single language (or only the released langs, etc), but i think in either case it would be good to pick either language or translation to refer to them

**Comment by flpm** [comment]
> minor thing: i wonder if we can pick one term to refer to a translation or language? 

Good point, that makes sense, maybe "languages" is more semantically correct?

**Comment by flpm** [comment]
I did a bit of reorganization of the nox sessions related to translations, to harmonize the names. I also simplified it a bit, to remove the internal build to release variable.

Here is the proposed setup:

- **update-language**: Update the PO files for a **single language** passed as a positional argument from the command line. E.g. `nox -s update-language -- es`. To be used by the language teams during early stages of the translation.
- **update-all-languages**: Update the PO files for **all languages in `LANGUAGES`.** To be used in dev, for tests.
- **update-all-release-languages**: Update the PO files for **all languages in `RELEASE_LANGUAGES`.** To be used in CI to keep PO files updated (see PR #397)
- **build-language**: Build the guide in a **single language** passed as a positional argument from the command line. E.g. `nox -s build-language -- es`. To be used in dev.
- **build-all-languages**: Build the guide for **all languages in `LANGUAGES`.** To be used in dev, for tests.
- **build-all-release-languages**: Build the guide for **all languages in `RELEASE_LANGUAGES`.** Called by the docs-test nox session, which is used in CI to build the guide for release.
- **build-all-languages-test**: A convenience function to run build-all-languages using the same parameters that docs-test used.

**Review by sneakers-the-rat — APPROVED** [review]
I like it - good with me :)

as an aside, since i'm not asking you to fix nox in this PR - the only thing i wish is that nox had a bit of a better way of sharing venvs, because each of these will make their own venv which makes things big and slow. making each of the sessions independent (rather than using `notify`) i think makes them tidier and easier to read than notify and posargs, which i like tho, so it's an improvement imo :)

**Review by tkoyama010 — APPROVED** [review]

**Comment by tkoyama010** [comment]
Thanks @flpm !

**Review by sneakers-the-rat — APPROVED** [review]

**Comment by sneakers-the-rat** [comment]
Wondering if we can merge this? i gave approval but i guess i don't have the right permissions or role or w/e to overcome the merge block.

**Comment by lwasser** [comment]
oh @sneakers-the-rat i'm just getting caught up on things. you should have permissions to merge. let me check right now.

**Comment by flpm** [comment]
I just realized that this change of nox session names should be reflected in the contributor translation guide. I will make that change and then we can merge!

**Comment by sneakers-the-rat** [comment]
@flpm how about you merge once you've made the changes you want :)

**Review by sneakers-the-rat — APPROVED** [review]

**Review by sneakers-the-rat — APPROVED** [review]
i'm just gonna keep approving this lol i like what you're up to

**Pull request merged**
