### PR TITLE
docs: translate to Japanese index.md

### PR DESCRIPTION
**Pull request by tkoyama010**
ref #352

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
@kozo2 Same with https://github.com/pyOpenSci/python-package-guide/pull/367#issuecomment-2282335731

**Review by kozo2 — COMMENTED** [review]
I have finished my review.
I have no comments on this PR.

**Comment by tkoyama010** [comment]
@all-contributors please add @kozo2 for translation

**Comment by tkoyama010** [comment]
@all-contributors please add @tkoyama010 for translation

**Review by willingc — APPROVED** [review]
Structure looks good. Thanks!

**Pull request merged**
