### PR TITLE
maint: ungoofy the header at intermediate widths

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
i had raised this with upstream here: https://github.com/pydata/pydata-sphinx-theme/pull/1784

but it's stalled because 🤷

currently at intermediate widths pydata-sphinx-theme does this whacky thing:

Screenshot 2024-08-22 at 11 26 09 PM

so this PR:

Screenshot 2024-08-22 at 11 26 36 PM

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by lwasser** [comment]
@sneakers-the-rat are you willing to submit this to our theme instead?
we can merge this here, but ideally, we will use the theme very soon for all things guidebooks. Then we only update sphinx theme things in one place 🎉 

This seems like a fix we want on the theme for our guide books. please let me know if you agree or not!! and thank you for this. 

https://github.com/pyOpenSci/pyos-sphinx-theme/issues

**Comment by lwasser** [comment]
so we can totally merge here but it would be better served in the theme!!

**Comment by lwasser** [comment]
all looks good! let's merge 🚀 thank you Jonny!!!

**Comment by sneakers-the-rat** [comment]
oh and also i would be happy to pull it over there too, i did take a look at it bc i thought i remembered you mentioning it, but didn't see it used here yet which is why i pulled it here

**Comment by lwasser** [comment]
@sneakers-the-rat thank you. that was a perfect decision! 

I see your pr over there now. i left a question about how this works with sphinx.  ✨

**Pull request merged**
